### ISSUE TITLE
Vectrex Extra, checks 514 times for the same file

### ISSUE THREAD

**Issue by lunchpacked130** [mattpannella/pupdate#277]
**Describe the bug**
When downloading and installing the Vectrex Extra assets with pupdate.exe (Version 3.9.0), the file "Blank_Overlay.ovr" is installed with the additional core, just before being checked for 514 times.

The file "Blank_Overlay.ovr" is just a single file used by any Vectrex roms that doesn't have a dedicated overlay, so if it`s possible, it should only be checked once.

**To Reproduce**
1. Run pupdate.exe
2. Select [7] Pocket Extras
3. Select [2] Variant Cores
5. Select [0] Download Vectrex Extras
6. When asked to install additional core select [Y]es

I have attached my own log export from pupdate.exe:
[Vectrex Extras Install Log.txt](https://github.com/mattpannella/pupdate/files/14560385/Vectrex.Extras.Install.Log.txt)

**Comment by hallem** [comment]
The reason the `Blank_Overlay.ovr` file is checked for that many times is because it's directly referenced by the instance json files that define many of the games included in the extras for the Vertex core.

Pupdate iterates through each json file and attempts to find the required files for each game and checks for their existence locally and if not found, download them. Unfortunately, this is a very unique issue that is specific to this set of extras and core.

Additionally, from your included log file, it looks like you still need to finish making the necessary changes to your settings file to get the rest of the files to download for you. If you check out the [readme](https://github.com/dyreschlock/pocket-extras/blob/main/vectrex_extras/README.md) for the Vectrex Extras, it will contain the instructions for you to follow.

**Comment by lunchpacked130** [comment]
Ah, that explain it, i just thought it might be a simple fix to ignore the other checks when it has checked ut once.

Also, please ignore any errors etc from ny log, i backed up the assets and reinstalled them to make the logs "from scratch" and doublecheck if i had done something wrong, 
all vectrex files are installed correctly and everything works for me.

I guess this issue can be closed now
