### ISSUE TITLE
Mac: "Pupdate is damaged and can't be opened"

### ISSUE THREAD

**Issue by Dochartaigh** [mattpannella/pupdate#302]
**Describe the bug**
pupdate will not run on Apple silicone running newest MacOS Sonoma 14.4.1

**To Reproduce**
1. Download newest 3.10.2 version for Mac ("pupdate_mac.zip"), unzip, and move to ROOT of SD card
2. Run pupdate (since it's an unknown developer you might have to go to Settings>Security to allow it to run, which I did!)
3. See ""Pupdate" is damaged and can't be opened"" error:

![Screenshot 2024-05-16 at 12 47 44 AM](https://github.com/mattpannella/pupdate/assets/23370177/71696967-ab12-4406-9f25-e6c61e6bb21d)

**Expected behavior**
I expect pupdate to run on my mac

**Screenshots**
(above)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - 14.4.1

**Contents of settings file**
That file isn't created since pupdate won't run, period.

**Comment by mattpannella** [comment]
did you try just re-downloading the release from github? it sounds like maybe the file is just corrupted

**Comment by mattpannella** [comment]
bump

**Comment by harperreed** [comment]
This is most likely due to the security quarantine that is default on osx. It is easy to bypass and fix. 

**Workaround**
To bypass the security quarantine on macOS, use the `xattr` command to remove the quarantine attribute from the downloaded file. Here's how:

1. Open Terminal.
2. Navigate to the directory containing the file:
    ```sh
    cd /Volumes/SDCARDDIR
    ```

3. Remove the quarantine attribute:
    ```sh
    xattr -d com.apple.quarantine ./pupdate
    ```

4. Run the updater:
    ```sh
    ./pupdate
    ```

After removing the quarantine attribute, you should be able to run the updater without encountering the "damaged and can't be opened" error.

**Comment by Dochartaigh** [comment]
Late reply to some of these posts I know, but thanks for the replies from all. I simply ran Parallels Desktop with Windows 11 on my Mac and it did everything I needed - haven't tried it on Mac again.

**Comment by jstewsy** [comment]
Adding on that after successfully running the command to remove `pupdate` from quarantine, I also had to run `./pupdate` with `sudo`. Incase any future folks get stuck at upgrading with macos
