### ISSUE TITLE
latest pupdate release (3.16) being flagged for virus

### ISSUE THREAD

**Issue by Truckondo** [mattpannella/pupdate#341]
![pupdate 3 16 0 virus](https://github.com/user-attachments/assets/b93d0e8c-8017-4228-97f1-2714318e16c5)

First time seeing a virus pop up on my computer in a good while.

**Comment by hallem** [comment]
So this happens intermittently and we're not able to consistently make it happen in order to understand what it thinks is the problem. Matt has submitted a whitelist request to Microsoft so we're waiting to see what happens with that. You can whitelist it locally on your computer by `Windows Security -> Virus & Threat Protection -> Manage Settings -> Exclusions` or something to that effect.

**Comment by mattpannella** [comment]
I looked up my submission status and it's just gone now lol
maybe I'll resubmit
